ENABLE_ENCODER?=1
ENABLE_DECODER?=1
ENABLE_ENC_HEVC?=1
ENABLE_ENC_AVC?=1
ENABLE_DEC_HEVC?=1
ENABLE_DEC_AVC?=1
ENABLE_ROI?=1
ENABLE_MICROBLAZE?=1
ENABLE_LIB_ISCHEDULER?=0
ENABLE_SYNC_IP?=1
ENABLE_HIGH_DYNAMIC_RANGE?=1
ENABLE_CLIENT_FLAG?=0
ENABLE_ENC_SW_MULTIPASS?=1
ENABLE_AVX2?=0
ENABLE_LINUX_DRIVER?=1
CFLAGS+=-w

ENABLE_AVC?=1
ENABLE_HEVC?=1
ENABLE_ENC_ITU?=1
ENABLE_DEC_ITU?=1
ENABLE_DEC_CODEC?=1
ENABLE_CODEC?=1

CONFIG=include/config.h
