plugins { id 'com.android.application' }

android {
    namespace 'com.fctvclean.updater'
    compileSdk 35

    defaultConfig {
        applicationId 'com.fctvclean.updater'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation 'com.android.tools.build:apksig:8.6.1'
}
